### ISSUE TITLE
config in 2.11 still not reloadable

### ISSUE THREAD

**Issue by ochaton** [moonlibs/config#27]
Tarantool 2.11.0-0-g247a9a418 Linux-aarch64-RelWithDebInfo

config.lua:101: Bad vars for function: 0x78dcc22b8780 after steps: mt_call

main/134/main/package.reload I> 2nd load. Unloading {digest, config.etcd, config, background, clock}
main/134/main/package.reload I> package.reload:cleanup...
main/134/main/package.reload I> package.reload:cleanup finished
main/134/main/config I> var raw_cfg=table: 0x3474c2546a50
main/134/main/config I> var proxy_table=table: 0x3474c2546be0
main/134/main/config I> var locked=function: 0x3474c26c3480
main/134/main/config I> var reload_cfg=function: 0x3474c2709188
main/135/lua/package.reload reload.lua:160 E> Cleanup 1, running

**Comment by ochaton** [comment]
@Mons please take a look

**Comment by Melliko** [comment]
We encountered the same issue. Please look into it, LTS version of tarantool, blocks our release.

Tarantool 2.10.6-0-g3990f97 Linux-x86_64-RelWithDebInfo
Host: Linux 3.10.0-1160.49.1.el7.x86_64 #1 SMP Tue Nov 30 15:51:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Error:
---
- error: '/usr/share/hb10years/libs/share/lua/5.1/config.lua:101: Bad vars for function:
    0x40dd9160 after steps: mt_call, ctl-orig_cfg_call, func'
...

**Comment by ochaton** [comment]
This issue was fixed in moonlibs/config 0.7.0
